---
title: "Exploratory Data Analysis"
author: "Eileen Shea"
date: "10/14/2018"
output: html_document
---

```{r}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_bw() + theme(legend.position = "bottom"))
```

Data import 

```{r data_import, cache = TRUE}
library(rnoaa)

weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, everything())
weather_df
```

## Start grouping

```{r}
weather_df %>% 
  group_by(name, month)
```

Counting...

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(number = n())

weather_df %>% 
  group_by(month) %>% 
  summarize(number = n())

weather_df %>% 
  count(month)
```

## Grouped summaries

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(number = n(),
            mean_tmax = mean(tmax, na.rm = TRUE),
            median_prcp = median(prcp, na.rm = TRUE),
            sd_tmin = sd(tmin, na.rm = TRUE))
```

This is still a tibble!!

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(number = n(),
            mean_tmax = mean(tmax, na.rm = TRUE),
            median_prcp = median(prcp, na.rm = TRUE),
            sd_tmin = sd(tmin, na.rm = TRUE)) %>% 
  ggplot(aes(x = month, y = mean_tmax, color = name)) +
  geom_point()
```

Alternatively, we can plot two tibbles at once...

```{r}
month_df = weather_df %>% 
  group_by(name, month) %>% 
  summarize(number = n(),
            mean_tmax = mean(tmax, na.rm = TRUE),
            median_prcp = median(prcp, na.rm = TRUE),
            sd_tmin = sd(tmin, na.rm = TRUE))

ggplot(weather_df, aes(x = date, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  geom_line(data = month_df, aes(x = month, y = mean_tmax))
```

Tidy is not always best for humans...

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(mean_tmax = mean(tmax, na.rm = TRUE)) %>% 
  spread(key = name, value = mean_tmax) %>% 
  knitr::kable(digits = 3)
```

## Group mutate

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  mutate(mean_tmax = mean(tmax, na.rm = TRUE))
```

More interesting example...

```{r}
weather_df %>% 
  group_by(name) %>% 
  mutate(mean_tmax = mean(tmax, na.rm = TRUE),
         centered_tmax = tmax - mean_tmax) %>% 
  ggplot(aes(x = date, y = centered_tmax, color = name)) +
  geom_point()
```

## Window functions

Use ranks...

to find the coldest days of each month!

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  mutate(tmax_rank = min_rank(tmax)) %>% 
  filter(tmax_rank < 2)
```

to find the warmest days of each month!

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  mutate(tmax_rank = min_rank(desc(tmax))) %>% 
  filter(tmax_rank < 2)
```

Use lags...

```{r}
weather_df %>% 
  group_by(name) %>% 
  mutate(lag_tmax = lag(tmax))
```

## How neat is this??

```{r}
weather_df %>% 
  group_by(name) %>% 
  mutate(one_day_change = tmax - lag(tmax)) %>% 
  summarize(sd_one_day_change = sd(one_day_change, na.rm = TRUE))
```

PULSE Learning Assessment:

```{r}
pulse_data = haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names() %>%
  gather(key = visit, value = bdi, bdi_score_bl:bdi_score_12m) %>%
  separate(visit, into = c("remove_1", "remove_2", "visit"), sep = "_") %>%
  select(id, visit, everything(), -starts_with("remove")) %>%
  mutate(visit = replace(visit, visit == "bl", "00m"),
         visit = factor(visit, levels = str_c(c("00", "01", "06", "12"), "m"))) %>%
  arrange(id, visit)

pulse_data %>% 
  group_by(visit) %>% 
  summarize(mean_bdi = mean(bdi, na.rm = TRUE),
            median_bdi = median(bdi, na.rm = TRUE)) %>% 
  knitr::kable(digits = 3)
```


