---
title: "Visualization Pt. 1"
author: "Eileen Shea"
date: "10/13/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggridges)
```

```{r data_import, cache = TRUE}
library(rnoaa)

weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
weather_df
```

## Start a plot

Blank plot...

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax))
```

Scatterplot...

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point()
```

Amenable to piping:

```{r}
weather_df %>% 
  filter(name == "CentralPark_NY") %>% 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()
```

Can also save plot:

```{r}
weather_sp =
  ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point()
```


## More plot options

Add an aesthetic:

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name))
```

Add a geom:

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name)) +
  geom_smooth(se = FALSE)
```

Add an option:

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = 0.4) +
  geom_smooth(se = FALSE)
```

Global coloring...

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.4) +
  geom_smooth(se = FALSE)
```

Facetting...

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.4) +
  geom_smooth(se = FALSE) +
  facet_grid( ~ name)
```

A more interesting plot:

```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name, size = prcp)) +
  geom_point() +
  geom_smooth(se = FALSE) +
  facet_grid(~name)
```

Learning assessment:

```{r}
weather_df %>% 
  filter(name == "CentralPark_NY") %>% 
  mutate(tmax_fahr = tmax * (9 / 5) + 32,
         tmin_fahr = tmin * (9 / 5) + 32) %>%
  ggplot(aes(x = tmin_fahr, y = tmax_fahr)) +
    geom_point(alpha = 0.5) +
    geom_smooth(method = "lm", se = FALSE)
```


## Univariate plots








